options:
  logging: CLOUD_LOGGING_ONLY

steps:

# run nomos hydrate
# prerequisites is that we should get nomos, kustomize and helm downloaded.
# in production please pin the versions
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud storage cp gs://config-management-release/released/latest/linux_amd64/nomos ./nomos
    chmod +x ./nomos
    
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod +x ./get_helm.sh
    ./get_helm.sh

    curl -fsSL -o install_kustomize.sh "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
    chmod +x ./install_kustomize.sh
    ./install_kustomize.sh /usr/local/bin/

    ./nomos hydrate --no-api-server-check --source-format unstructured --path off-cluster/config --output /workspace/compiled

# get the output of the hydration into a tar file, needed for crane.
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    tar -cvf /workspace/compiled.tar /workspace/compiled/

# package up the contents into an image
- name: 'gcr.io/go-containerregistry/crane'
  args: ['append', '-f',  '/workspace/compiled.tar', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/ar1/hydrated:latest']
