options:
  logging: CLOUD_LOGGING_ONLY

steps:

# copy the configuration into a writeable directory because
# of the kustomize caching.
- name: 'ubuntu' # Or another image with `cp`
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cp -r off-cluster/config /workspace/config 

# run nomos hydrate
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud storage cp gs://config-management-release/released/latest/linux_amd64/nomos ./nomos
    chmod +x ./nomos
    
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod +x ./get_helm.sh
    ./get_helm.sh

    curl -fsSL -o install_kustomize.sh "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
    chmod +x ./install_kustomize.sh
    ./install_kustomize.sh

    ./nomos hydrate --no-api-server-check --source-format unstructured --path /workspace/config --output /workspace/compiled

# get the output of the hydration into a tar file, needed for crane.
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    tar -cvf /workspace/compiled.tar /workspace/compiled/

# package up the contents into an image
- name: 'gcr.io/go-containerregistry/crane:v0.20.2'
  args: ['append', '-f',  '/workspace/compiled.tar', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/ar1/hydrated:latest']
