options:
  logging: CLOUD_LOGGING_ONLY

steps:

# run nomos hydrate
- name: 'gcr.io/config-management-release/nomos:v1.19.2'
  args: ['hydrate', '--source-format', 'unstructured', '--path', 'off-cluster/config']

# get the output of the hydration into a tar file, needed for crane.
- name: 'gcr.io/cloud-builders/tar'
  args: ['-cvf', 'compiled.tar', 'compiled/']

# package up the contents into an image
- name: 'gcr.io/go-containerregistry/crane:v0.20.2'
  args: ['append', '-f',  'compiled.tar', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/ar1/hydrated:latest']